# Site settings
title: "Chenxiao Yu"
email: "cyu96374@usc.edu"
description: >- # This means to ignore newlines until "baseurl:"
  Welcome to my academic homepage! I am a graduate student at the University of Chicago,
  studying Computational Analysis and Public Policy. My research focuses on AI, NLP,
  and Bayesian networks.

# GitHub Pages URL settings
baseurl: "/ChenxiaoYu.github.io" # The subpath of your site (if it's inside a GitHub subfolder)
url: "https://aichimocha.github.io" # The base domain for your site

# Social media (Optional)
twitter_username: ""
github_username: "aichimocha"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
